### ISSUE TITLE
Document how to run functional tests

### ISSUE THREAD

**Issue by macterra** [Equibit/equibit#110]
Create a How-to article in Confluence to help developers run and debug the functional tests.

![image.png](https://images.zenhubusercontent.com/5b7b0c90e11d522c0690b270/df7ad1b1-726a-4b33-b61f-a2484da3a97d)

**Comment by ealefad** [comment]
Initial version added to Confluence
https://confluence.equibitgroup.com/x/iIEh

**Comment by ealefad** [comment]
Updated chapter 2. Windows
